export const Memorycardpic = require ('./memorycard.png')
export const LIClone = require ('./li-clone.png')
export const Portfolio = require ('./portfolio.png')
export const LinkedIn = require ('./linkedin.png')
export const GitHub = require ('./github.png')
export const Gmail = require ('./gmail.png')
export const starry = require ('./starry.jpg')
export const headshot =require('./headshot.jpg')